### PR TITLE
Intergrate ZooKeeper configuration file with Beyond configuration file.

### PR DESCRIPTION
**Pull request by sgkim126**
Current ZooKeeper configuration is difficult because there are many config files to use ZooKeeper.
This patch intergrates zookeeper configuration files with the beyond framework file.

### CODE REVIEW

**Comment by noraesae** [comment]
The concept looks very good. Could you update the PR as it may conflict with my patches? After that I'll look into it more specifically.

**Comment by sgkim126** [comment]
@noraesae, I reupdated PR.

**Comment by noraesae** [comment]
Everything else looks good to me.

**Comment by sgkim126** [comment]
@noraesae PR updated.
I removed BeyondConfiguration.zooKeeperConfigPath, and modified to use config.configuration function to remove duplicated code.

**Comment by noraesae** [comment]
LGTM

**Pull request merged**
