### PR TITLE
Move plugin configuration option to dev.conf and test.conf

### PR DESCRIPTION
**Pull request by sgkim126**
It cause #213 issue.

### CODE REVIEW

**Comment by sgkim126** [comment]
Sorry, because I'm on the phone, I cannot launch test.
Please merge it after travis pass.

**Comment by noraesae** [comment]
I'm not sure why it fails. Any idea?

**Comment by noraesae** [comment]
Doesn't work in the master branch too.

**Comment by murmur76** [comment]
Now travis pass

**Pull request merged**
